from pathlib import Path
import re, json
s=Path(__file__).parent
t=(s/'306-revisado.md').read_text(encoding='utf-8')
def replace(old,new):
    global t
    assert old in t,old[:100]
    t=t.replace(old,new)
replace('AC de empleo (IDs a reservar al escribir spec)', 'AC-EMP-017–022')
replace('AC de limpieza (IDs a reservar)', 'AC-CLN-040–046')
replace('- `CicloDeJornadas.signal turno_agotado', '- `Agarre.cuerpo_sostenido() -> Node3D` devuelve el cuerpo EXACTO actual o null sin mutar estado. Soltar, entregar y vaciar dejan null; mover a examen y devolver conservan identidad. No se compara el Resource de datos: dos cajas comparten ese recurso y siguen siendo cuerpos distintos. El espejo pasa de18 a19 públicos, la fuente de8 a9, ambos dentro20. El rojo usa firma stub válida antes de implementar el lector.\n- `CicloDeJornadas.signal turno_agotado')
replace('No filtra por visibilidad de malla individual.', 'No filtra por visibilidad de malla individual. El estado en_mano usa identidad de cuerpo: `nodo == _agarre.cuerpo_sostenido() and not _jugador.examen.esta_examinando()`. Examen.iniciar sólo inicia sobre ese cuerpo y conserva la referencia del Agarre; durante el examen ese cuerpo cuenta por su posición física, frente a la cara. Se ejerce examen.iniciar real, no un flag fingido ni comparación por Resource.')
replace('No mantiene una segunda lista mutable en la raíz ni lee `_tirados` privado.', 'No mantiene una segunda lista mutable en la raíz ni lee `_tirados` privado. La foto local de candidatos incorpora además cuerpo_sostenido() sólo si sus datos son UnidadDeProducto y no está ya incluido por identidad: una unidad levantada sale de los grupos sueltos y debe volver a considerarse mientras se examina. Cajas, útiles y bolsas ya están en los arrays exportados. Ticket queda fuera de este candidato adicional y se incorpora en307 con su lector activo. Esto no agrega ownership ni una lista persistente a la raíz. Se copian clase, habitación y condición de mano antes de aplicar las reglas.')
replace('- [ ] Una unidad apoyada sobre una caja/góndola', '- [ ] Dos cajas con el MISMO Resource de datos siguen siendo cuerpos distintos: sostener una excluye sólo esa, y la otra desordenada o afuera sigue generando su motivo. El getter público de Agarre conserva identidad al mover/devolver y devuelve null tras soltar/entregar/vaciar. Examen.iniciar real hace contar ese mismo cuerpo por su posición, aunque Agarre conserve su referencia; al terminar el examen vuelve la exclusión de mano.\n- [ ] Una unidad apoyada sobre una caja/góndola')
replace('- [ ] `docs/architecture/capacidades.md` agrega', '- [ ] La prueba heredada de Mancha que prohíbe todo if/elif/match en almacen.gd se reemplaza: se conserva y renombra la comprobación de espejos, y se retira esa prohibición lexical. Las suites funcionales de cierre y el espejo puro verifican las decisiones; la revisión de capas/fuente confirma la delegación. No se agrega otra prueba textual de arquitectura.\n- [ ] `docs/architecture/capacidades.md` agrega')
writes=['specs/employment-record/employment-record.md','specs/store-cleanup/store-cleanup.md','docs/architecture/capacidades.md','src/dominio/reglas.gd','src/dominio/empleo/legajo.gd','src/dominio/empleo/partida.gd','src/dominio/empleo/partida_serializada.gd','src/dominio/empleo/politica_de_guardado.gd','src/dominio/almacen/reglas_del_cierre.gd','src/dominio/almacen/reglas_del_cierre.gd.uid','src/escenas/puestos/habitaciones_del_almacen.gd','src/escenas/puestos/habitaciones_del_almacen.gd.uid','src/sistemas/marco/ciclo_de_jornadas.gd','src/sistemas/marco/agarre.gd','src/escenas/almacen.gd','src/escenas/almacen.tscn','src/escenas/puestos/estructura_del_almacen.tscn','src/escenas/puestos/exterior_del_almacen.gd','src/escenas/puestos/reposicion_manual.gd','test/dominio/reglas_test.gd','test/dominio/empleo/legajo_test.gd','test/dominio/empleo/partida_test.gd','test/dominio/empleo/partida_serializada_test.gd','test/dominio/empleo/parte_de_cierre_test.gd','test/dominio/empleo/politica_de_guardado_test.gd','test/sistemas/marco/ciclo_de_jornadas_test.gd','test/sistemas/marco/agarre_test.gd','test/sistemas/marco/guardado_test.gd','test/sistemas/marco/enlace_de_guardado_test.gd','test/escenas/almacen_test.gd','test/escenas/objetos/mancha_en_el_piso_test.gd']
new_tests=['test/dominio/almacen/reglas_del_cierre_test.gd','test/escenas/puestos/habitaciones_del_almacen_test.gd','test/dominio/empleo/llamados_de_la_partida_test.gd','test/escenas/cierre_del_almacen_test.gd','test/escenas/unidades_sueltas_del_cierre_test.gd','test/escenas/soporte_del_exterior_test.gd']
for gd in new_tests:
    writes.extend([gd,gd+'.uid'])
reads=['src/sistemas/tareas/recolector_de_basura.gd','src/escenas/puestos/contenedor_de_basura.gd','src/escenas/puestos/tapa_del_contenedor.gd','src/escenas/jugador.gd','src/escenas/objetos/objeto_agarrable.gd','src/escenas/objetos/caja_de_productos.gd','src/escenas/objetos/util_de_limpieza.gd','src/escenas/objetos/grupo_del_piso.gd','src/escenas/objetos/ticket.tscn','src/escenas/puestos/ventanilla.gd','src/escenas/puestos/caja_registradora.gd','src/sistemas/investigacion/examen.gd','src/sistemas/marco/red_de_seguridad.gd','src/sistemas/marco/enlace_de_guardado.gd','src/sistemas/marco/guardado.gd','src/dominio/empleo/parte_de_cierre.gd','src/dominio/empleo/catalogo_de_reacciones.gd','src/dominio/empleo/consecuencia.gd','src/dominio/empleo/reaccion.gd','specs/save-and-resume/save-and-resume.md','specs/store-stock/store-stock.md','specs/player-actions/player-actions.md','specs/notifications/notifications.md','test/escenas/reposicion_manual_test.gd','test/escenas/modelo_integrado_test.gd','test/escenas/agarre_fisico_test.gd','test/escenas/notificaciones_en_el_almacen_test.gd','test/ui/pila_de_notificaciones_test.gd']
no=['src/escenas/almacen.lmbake','src/escenas/almacen.exr','assets/','project.godot','src/escenas/jugador.tscn','src/escenas/puestos/objetos_del_almacen.tscn','src/escenas/puestos/limpieza_del_almacen.tscn','src/escenas/puestos/servicios_del_almacen.tscn','src/escenas/puestos/interfaz_del_almacen.tscn','src/ui/','.claude/skills/']
assert all(Path(p).exists() for p in reads),[p for p in reads if not Path(p).exists()]
a=t.index('| Categoría | Rutas |'); b=t.index('## Verificación',a)
t=t[:a]+'| Categoría | Rutas |\n|---|---|\n'+''.join('| '+label+' | '+'; '.join('`'+r+'`' for r in routes)+' |\n' for label,routes in [('Se escribe',writes),('Sólo lectura',reads),('No se toca',no)])+'\nLos archivos nuevos son ocho GDScript con sus UID: dos fuentes y seis suites temáticas. No se agregan casos a Almacen30 (excepción heredada), ReposicionManual20 ni Inventario21; los casos nuevos se separan por función. Legajo15 admite hasta cinco, Partida17 hasta tres, Agarre18 hasta dos (se agrega uno), Serializada5, Parte9, Politica3, Ciclo5, Guardado10 y Enlace5 permanecen dentro20. Los tests actuales de enteros conservan sus valores de apercibimientos al migrar a medios: se multiplica por dos, no se reinterpretan3 como1,5. El espejo de Agarre y el test funcional de dos cuerpos con datos compartidos cubren ownership de identidad.\n\n'+t[b:]
replace('Medición B295/B300: 20 líneas en 10 archivos (`b-306-readers-295.txt`); recontar sobre305 final.', 'Medición readonly de30511301e9d:20 coincidencias precisas en10 archivos (`b-306-readers-305.json`); el enum sin prefijo se migra también. No se barre el sustantivo legítimo apercibimientos ni sus constantes de puntos enteros.')
replace('Jugador/guard297 y gesto/caja304 se conservan.', 'Jugador/guard297 y gesto/caja304 se conservan. Agarre sólo agrega el lector readonly aprobado; no altera movimientos, señales ni física.')
(s/'306-whole-preparado.md').write_text(t,encoding='utf-8')
(s/'b-306-alcance-preparado.json').write_text(json.dumps({'write':writes,'read':reads,'no':no},indent=2),encoding='utf-8')
print('External WHOLE306 draft',len(writes),'write',len(reads),'read')
