func test_papel_repetido_es_un_medio_y_afuera_es_otro() -> void:  # AC-CLN-047
	var partida := Partida.nueva()
	partida.abrir_la_jornada()
	partida.anotar_llamado(Partida.Llamado.PAPEL_EN_EL_INODORO)
	partida.anotar_llamado(Partida.Llamado.PAPEL_EN_EL_INODORO)
	partida.anotar_llamado(Partida.Llamado.OBJETO_AFUERA)
	partida.cerrar_la_jornada(partida.obligatorias().size())
	assert_int(partida.medios()).is_equal(2)
	partida.abrir_la_jornada()
	partida.anotar_llamado(Partida.Llamado.PAPEL_EN_EL_INODORO)
	partida.cerrar_la_jornada(partida.obligatorias().size())
	assert_int(partida.medios()).is_equal(3)


# AC-CLN-047, AC-CLN-049
func test_papel_fuera_de_noche_o_con_partida_terminada_no_se_guarda() -> void:
	var partida := Partida.new(Legajo.con_medios(7))
	partida.anotar_llamado(Partida.Llamado.PAPEL_EN_EL_INODORO)
	partida.abrir_la_jornada()
	partida.cerrar_la_jornada(partida.obligatorias().size())
	assert_int(partida.medios()).is_equal(7)
	partida.anotar_llamado(Partida.Llamado.PAPEL_EN_EL_INODORO)
	partida.abrir_la_jornada()
	partida.cerrar_la_jornada(partida.obligatorias().size())
	assert_int(partida.medios()).is_equal(7)
	partida.abrir_la_jornada()
	partida.anotar_llamado(Partida.Llamado.PAPEL_EN_EL_INODORO)
	partida.cerrar_la_jornada(partida.obligatorias().size())
	assert_int(partida.medios()).is_equal(8)
	assert_bool(partida.terminada()).is_true()
	partida.anotar_llamado(Partida.Llamado.PAPEL_EN_EL_INODORO)
	partida.cerrar_la_jornada(0)
	assert_object(partida.abrir_la_jornada()).is_null()
	assert_int(partida.medios()).is_equal(8)
